project_id                   = "positive-nuance-430214-r6"
project_name                 = " My Project 90990"
region                       = "us-central1"
bucket_name                  = "gcpdevops-engineer-bucket"
google_credential            = "key.json"
google_sql_database_instance = "devops-mysql"
db_password                  = "Root@123"
